language: python
os:
  - linux

addons:
  apt:
    packages:
      - xclip
      - xsel
      - xvfb

jobs:
  include:
    - os: osx
      language: generic
      env: PYTHON=3.8.0 PYGAME_VERSION=2.0.0
      before_install:
        - brew update
        - brew install openssl readline
        - brew outdated pyenv || brew upgrade pyenv
        - brew install pyenv-virtualenv
        - pyenv install $PYTHON
        - export PYENV_VERSION=$PYTHON
        - export PATH="/Users/travis/.pyenv/shims:${PATH}"
        - pyenv virtualenv py_venv
        - source /Users/travis/.pyenv/versions/py_venv/bin/activate
        - python --version
    - os: osx
      language: generic
      env: PYTHON=3.7.5 PYGAME_VERSION=2.1.0
      before_install:
        - brew update
        - brew install openssl readline
        - brew outdated pyenv || brew upgrade pyenv
        - brew install pyenv-virtualenv
        - pyenv install $PYTHON
        - export PYENV_VERSION=$PYTHON
        - export PATH="/Users/travis/.pyenv/shims:${PATH}"
        - pyenv virtualenv py_venv
        - source /Users/travis/.pyenv/versions/py_venv/bin/activate
        - python --version
    - os: windows
      language: shell
      before_install:
        - choco install python3 --params "/InstallDir:C:\\Python"
        - export PATH="/c/Python:/c/Python/Scripts:$PATH"
        - python --version
      env: PYGAME_VERSION=2.1.0
    - os: windows
      language: shell
      before_install:
        - choco install python3 --params "/InstallDir:C:\\Python"
        - export PATH="/c/Python:/c/Python/Scripts:$PATH"
        - python --version
      env: PYGAME_VERSION=2.0.0

    - os: linux
      python: 3.6
      env: PYGAME_VERSION=2.0.0
    - os: linux
      python: 3.6
      env: PYGAME_VERSION=2.1.0
    - os: linux
      python: 3.7
      env: PYGAME_VERSION=2.0.0
    - os: linux
      python: 3.7
      env: PYGAME_VERSION=2.1.0
    - os: linux
      python: 3.8
      env: PYGAME_VERSION=2.0.0
    - os: linux
      python: 3.8
      env: PYGAME_VERSION=2.1.0
    - os: linux
      python: 3.9
      env: PYGAME_VERSION=2.0.0
    - os: linux
      python: 3.10
      env: PYGAME_VERSION=2.1.2

install:
  - python -m pip install -U pip
  - python -m pip install pytest
  - python -m pip install pytest-cov
  - python -m pip install codecov
  - python -m pip install python-i18n
  - python -m pip install -q pygame==$PYGAME_VERSION
  - python setup.py -q install

env:
  global:
    - SDL_VIDEODRIVER=dummy
    - SDL_AUDIODRIVER=disk


script:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]];
    then xvfb-run pytest;
    else python -m pytest --cov-report=xml --cov=pygame_gui tests/;
    fi

after_success:
    - codecov