name: Run Tests 
on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.6, 3.7, 3.8, 3.9]
        pygame-version: [2.0.0, 2.1.0, 2.1.2]
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
        pygame-version: ${{ matrix.pygame-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install stringify
        python -m pip install python-i18n
        python -m pip install pytest
        python -m pip install pytest-cov
        python -m pip install codecov
        python -m pip install -q pygame==${{ matrix.pygame-version }}
        python setup.py -q install
        sudo apt-get install xvfb
        sudo apt-get install xclip
        sudo apt-get install xsel
    - name: Test with pytest
      env:
        SDL_VIDEODRIVER: dummy
        SDL_AUDIODRIVER: disk
      run: |
        xvfb-run pytest --cov-report=xml --cov=pygame_gui tests/
    - name: Upload to Code Cov
      uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }} #required
